{% set version = "20.4.1" %}
{% set sha256 = "a7f3333f01037b088dc9701eae2cc46e2cc6a784554df16fc61a1a07c52e87b9" %}

package:
  name: packmol
  version: {{ version }}

source:
  url: https://github.com/m3g/packmol/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - cmake
    - make

test:
  commands:
    - which packmol

about:
  home: http://m3g.iqm.unicamp.br/packmol
  license: MIT
  license_file: LICENSE
  license_family: BSD
  summary: Packing Optimization for Molecular Dynamics Simulations

extra:
  recipe-maintainers:
    - bgruening
    - kyleabeauchamp
    - mikemhenry
    - mattwthompson
