{% set version = "20.2.2" %}
{% set sha256 = "129cc1b7e6b00c1740c5c6f285a2c6207e18f05cdeb71af8107c3fedf48f23de" %}

package:
  name: packmol
  version: {{ version }}

source:
  url: https://github.com/m3g/packmol/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cmake
    - make

test:
  commands:
    - which packmol

about:
  home: http://m3g.iqm.unicamp.br/packmol
  license: MIT
  license_file: LICENSE
  license_family: BSD
  summary: Packing Optimization for Molecular Dynamics Simulations

extra:
  recipe-maintainers:
    - bgruening
    - kyleabeauchamp
    - mikemhenry
    - mattwthompson
