{% set version = "20.15.1" %}
{% set sha256 = "bee21629379d2c5cd463f6350094057f8a85b990ab882b822149a9bebe5bda8a" %}

package:
  name: packmol
  version: {{ version }}

source:
  url: https://github.com/m3g/packmol/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0000-use-packmol-from-path.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - cmake
    - make

test:
  requires:
    - julia
  files:
    - test.sh
  commands:
    - which packmol
    - bash test.sh 

about:
  home: http://m3g.iqm.unicamp.br/packmol
  license: MIT
  license_file: LICENSE
  license_family: BSD
  summary: Packing Optimization for Molecular Dynamics Simulations

extra:
  recipe-maintainers:
    - bgruening
    - kyleabeauchamp
    - mikemhenry
    - mattwthompson
