{% set version = "21.0.0" %}
{% set sha256 = "5c751ec7f4e6960837c3579237d36449d1b37cfa240fb9590f74f558dc1fe155" %}

package:
  name: packmol
  version: {{ version }}

source:
  url: https://github.com/m3g/packmol/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0000-use-packmol-from-path.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - cmake
    - make

test:
  files:
    - test.sh
  commands:
    - which packmol
    - bash test.sh  # [not ppc64le]

about:
  home: http://m3g.iqm.unicamp.br/packmol
  license: MIT
  license_file: LICENSE
  license_family: BSD
  summary: Packing Optimization for Molecular Dynamics Simulations

extra:
  recipe-maintainers:
    - bgruening
    - kyleabeauchamp
    - mikemhenry
    - mattwthompson
