{% set version = "21.1.2" %}
{% set sha256 = "8999c01c5a6b25575d31019089ee7c056b421232bdc9f9d9a2a8799d76cf1184" %}

package:
  name: packmol
  version: {{ version }}

source:
  url: https://github.com/m3g/packmol/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0000-use-packmol-from-path.patch
    - patches/0001-update-cmake-min-version.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - cmake
    - make

test:
  files:
    - test.sh
  commands:
    - which packmol
    - bash test.sh  # [not ppc64le]

about:
  home: http://m3g.iqm.unicamp.br/packmol
  license: MIT
  license_file: LICENSE
  license_family: BSD
  summary: Packing Optimization for Molecular Dynamics Simulations

extra:
  recipe-maintainers:
    - bgruening
    - kyleabeauchamp
    - mikemhenry
    - mattwthompson
