{% set version = "21.0.2" %}
{% set sha256 = "4b63d73400f7702347d9ff0cc4d0009be5a752afa7af00ad612554e8918f00fd" %}

package:
  name: packmol
  version: {{ version }}

source:
  url: https://github.com/m3g/packmol/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0000-use-packmol-from-path.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - cmake
    - make

test:
  files:
    - test.sh
  commands:
    - which packmol
    - bash test.sh  # [not ppc64le]

about:
  home: http://m3g.iqm.unicamp.br/packmol
  license: MIT
  license_file: LICENSE
  license_family: BSD
  summary: Packing Optimization for Molecular Dynamics Simulations

extra:
  recipe-maintainers:
    - bgruening
    - kyleabeauchamp
    - mikemhenry
    - mattwthompson
