schema_version: 1

context:
  version: "21.2.1"
  sha256: 6b8275be64e425fd578e7606ac22bb586108bc6b5c17d417873bd108928f830f

package:
  name: packmol
  version: ${{ version }}

source:
  url: https://github.com/m3g/packmol/archive/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
    - patches/0000-use-packmol-from-path.patch
    - patches/0001-update-cmake-min-version.patch

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('fortran') }}
    - ${{ stdlib("c") }}
    - cmake
    - make

tests:
  - files:
      recipe:
        - test.sh
    script:
      - which packmol
      - if: not ppc64le
        then: bash test.sh

about:
  license: MIT
  license_file: LICENSE
  summary: Packing Optimization for Molecular Dynamics Simulations
  homepage: http://m3g.iqm.unicamp.br/packmol

extra:
  recipe-maintainers:
    - bgruening
    - kyleabeauchamp
    - mikemhenry
    - mattwthompson
