appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: g+AjjNlI31ch9KUKRj5M//W1ipM5OnIpTEnuO5h1NewO28G8VHFqV/bBEKnURprqvaBrDuKN+QKMn9VIgbs3lN4zzCTdHJptRxoFr3zpnO3uHqltHleZRouaw/SRB53DEKbFcaNkNPcB7P70AwV/lRDAekg2FAScb5/vzTZ8ud/nNkb2Ma94omFAlyo97Crn0APrr871rPd2K3BIZ8aMDC1rOtV8vxjP7EDj5+DX7iMmpATbitDSKNkIema9hCJh2m+QbGpsxOZNjuaBTR7KDQJRE1t5PvOUmemMAjaNgAyXsbcGY08ifFSkLcQ9AYw0C7L5OBq5HNSj3rwAVOL0Dpwx7gf9SNqENZgeGuaGZYCAXwXEd2X7cKdEJb5TPtZqrILDEnBwA44JBPlQ59VlR7p3JS3iHHy3edR4znWPl1o7dSnxtW7ttI5KwO0w7JOiOZhuxNwHhdbzlysWwhh2Jd1eHIyXQ4iXuzQhmBYw4Y0dUwHQCr6E9iE6ObGdB3W8Kh6G6UO7vEZf1VgXz4+XRCZedSMQjnUW3QYiqXqqd6CrxjdpnB+4DBCy5Y2SwPiwilkhUKoX6uQUzNF1D5I2HOliq66IjiUPMl8Go+EiQ88diGREZ3RXmUXlhZlnlcmpKSQLRAyGE7Dgslz1LnPD6azcgu3g/SbDazhmABAhx0c=}
